- name: Create template output directory
  file:
    path: "{{ smatrix_template_dest_dir }}"
    state: directory
  loop: "{{ smatrix_dimensions | dict2product }}"
  when: not item | is_subset_in(smatrix_exclude)

- name: Create templates
  include_tasks: template-files.yml
  loop: "{{ smatrix_dimensions | dict2product }}"
  when: not item | is_subset_in(smatrix_exclude)
