---
driver:
  name: delegated # see https://molecule.readthedocs.io/en/latest/configuration/#delegated
platforms:
  - name: fake # must define a platform, even though we don't need one
provisioner:
  name: ansible
verifier:
  name: ansible
